version: '2'

services:
  # web:
  #   image: nginx:latest
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   links:
  #     - travian

  travian:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: travian
    ports:
      - '8080:80'

  mysql:
    image: mysql:8.3
    container_name: travian-sql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=travian
        - MYSQL_USER=travian
        - MYSQL_PASSWORD=travian
    # volumes:
    #     - ./appdata/mysql/data:/var/lib/mysql
